### ISSUE TITLE
Terminal not working after Atom 1.12.0 update

### ISSUE THREAD

**Issue by kutsan** [vertexclique/tokamak-terminal#10]
The only thing that I can see, this.

![image](https://cloud.githubusercontent.com/assets/10108377/20174828/7c0b8a16-a748-11e6-8c11-e27a2a57fb92.png)

**Comment by jmzhang** [comment]
It seems to be the problem of the dependency on pty.js. I fixed the problem by modifying this line:

```
 "pty.js": "https://github.com/platformio/pty.js/tarball/22e84bd6ef177c7c211a767564ffe64426cb8a69",
```

to

```
 "pty.js": "https://github.com/platformio/pty.js/tarball/prebuilt",
```

in `~/.atom/packages/tokamak-terminal/package.json`. Then delete the node_modules folder and do a fresh npm install from there. 

The terminal from platformio is also a good alternative, but unfortunately only tokamak work with the ui theme I love, the two packages have almost identical source code, not sure why 🤔

**Comment by kutsan** [comment]
@jmzhang Thanks fixed the problem. I wonder where @vertexclique is.

**Comment by flying-sheep** [comment]
hmm, i still get

```
Warning: Module version mismatch. Expected 50, got 51.
Error: Cannot find module '../bin/linux/x64.m50.node'
TypeError: Cannot read property 'bind' of null
```

@vertexclique is back, at least on twitter: https://twitter.com/vertexclique

**Comment by flying-sheep** [comment]
i fixed it by just depending on `"pty.js": "^0.3.1"`, deleting `node_modules`, and running `apm i`

**Comment by cdrandin** [comment]
Despite it working as a quick fix. It seems it had more implications, at least in my case. Causing electron to not work properly when trying to run it through the plugin terminal.

[`stackoverflow`](https://stackoverflow.com/questions/40664009/requireelectron-app-is-undefined-i-npm-installed-fresh-modules-unsure-what/40664925#40664925)

**Comment by sinlov** [comment]
```sh
cd ~/.atom/packages/tokamak-terminal
# or In Setting Packages/Tokamak Terminal Click View Code
```

change `package.json` to

```json
"dependencies": {
    "atom-space-pen-views": "^2.1.0",
    "pty.js": "https://github.com/platformio/pty.js/tarball/prebuilt",
    "term.js": "https://github.com/jeremyramin/term.js/tarball/master",
    "underscore": "^1.8.3"
  },
```

```json
{
        "name": "pty.js",
        "version": "^0.3.1",
        "path": "node_modules/pty.js/index.js"
      },
```

than in `~/.atom/packages/tokamak-terminal`

```sh
cd ~/.atom/packages/tokamak-terminal
rm -rf node_modules
apm i
```

**Comment by Wabuo** [comment]
@sinlov Where should I put the second code block?

**Comment by vertexclique** [comment]
updated in `v10.0.1`

**Comment by sinlov** [comment]
@Wabuo just update version of `pty.js` and rebuild.
